
CREATE DATABASE IF NOT EXISTS mundo_dastelas DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mundo_dastelas;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
